Integration of Regis patches Irene

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,8 +310,8 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE YACC CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT AWK INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S RANLIB ac_ct_RANLIB CP MV RM MKDIR ECHO CAT CHMOD SED AR DIFF EGREP ALLOCA LIBOBJS AMAYAOS AMAYAGUI GTKCONFIG_FOUND GTK_INCLUDES GTK_LIBRARIES GL_BUILDDIR GL_INCLUDES GL_LIBRARIES WXCONFIG WX_SRCDIR WX_BUILDDIR BUILDWXWIDGETS WX_INCLUDES WX_LIBRARIES WX_LINKDEPS LIBJPEG LIBPNG LIBZ MAKEJPEG MAKEPNG GTK_GL_INCLUDES GTK_GL_LIBRARIES FREETYPE_INCLUDES FREETYPE_LIBRARIES XFT_INCLUDES XFT_LIBRARIES PRINTIFNOTGL NOPRINT AMAYA_INSTALLDIR APP_MAJVER APP_MINVER APP_SUBVER APP_VER CEXTRACT_VER CEXTRACT_FLAGS THOTINCLUDES APIINCLUDES VPATHOPT GTK_OPTIONS THOT_OPTIONS AMAYA_OPTIONS PLUGIN_OPTIONS AMAYA_ANNOT_OPTIONS AMAYA_ANNOT_INCLUDES AMAYA_ANNOT_EXTRA_LIBS IMGLIBS EXTRA_LIBS EXTRA_INCLUDES DAVDIR LIBDAV WITHDAV WWWDAV MAKERAPTOR MAKEREDLAND ANNOTLIB_COMPILE_BM AMAYA_RAPTOR_SRC AMAYA_RAPTOR_LIBS AMAYA_RAPTOR_INCLUDES MAKE_LIBWWW_RDF_PARSER LIBWWW_RDF_PARSER SUBDIRS EXTRA_MAKEFILE_IN LTLIBOBJS'
-ac_subst_files='plugin_frag www_frag math_frag svg_frag annot_frag dav_frag templates_frag'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SET_MAKE YACC CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT AWK INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S RANLIB ac_ct_RANLIB CP MV RM MKDIR ECHO CAT CHMOD SED AR DIFF EGREP ALLOCA LIBOBJS AMAYAOS AMAYAGUI GTKCONFIG_FOUND GTK_INCLUDES GTK_LIBRARIES GL_BUILDDIR GL_INCLUDES GL_LIBRARIES WXCONFIG WX_SRCDIR WX_BUILDDIR BUILDWXWIDGETS WX_INCLUDES WX_LIBRARIES WX_LINKDEPS LIBJPEG LIBPNG LIBZ MAKEJPEG MAKEPNG GTK_GL_INCLUDES GTK_GL_LIBRARIES FREETYPE_INCLUDES FREETYPE_LIBRARIES XFT_INCLUDES XFT_LIBRARIES PRINTIFNOTGL NOPRINT AMAYA_INSTALLDIR APP_MAJVER APP_MINVER APP_SUBVER APP_VER CEXTRACT_VER CEXTRACT_FLAGS THOTINCLUDES APIINCLUDES VPATHOPT GTK_OPTIONS THOT_OPTIONS AMAYA_OPTIONS AMAYA_ANNOT_OPTIONS AMAYA_ANNOT_INCLUDES AMAYA_ANNOT_EXTRA_LIBS IMGLIBS EXTRA_LIBS EXTRA_INCLUDES DAVDIR LIBDAV WITHDAV WWWDAV MAKERAPTOR MAKEREDLAND ANNOTLIB_COMPILE_BM AMAYA_RAPTOR_SRC AMAYA_RAPTOR_LIBS AMAYA_RAPTOR_INCLUDES MAKE_LIBWWW_RDF_PARSER LIBWWW_RDF_PARSER SUBDIRS EXTRA_MAKEFILE_IN LTLIBOBJS'
+ac_subst_files='www_frag math_frag svg_frag annot_frag dav_frag templates_frag'
 
 # Initialize some variables set by options.
 ac_init_help=
@@ -867,6 +867,13 @@ Optional Features:
   --enable-bookmarks      enables experimental bookmark support
   --disable-templates     disables experimental templates support
   --disable-generic-xml   remove Generic XML support
+  --disable-svg           disable SVG support
+  --disable-annot         disable Annotations support
+  --disable-redland       disable redland RDF support
+  --enable-bookmarks      enable experimental bookmark support
+  --disable-templates     disable experimental templates support
+  --disable-generic-xml   disable Generic XML support
+  --enable-system-redland try the redland RDF system library
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -875,7 +882,6 @@ Optional Packages:
   --with-gtk              use GTK GUI toolkit
   --with-wx               use wxWidgets GUI toolkit
   --with-mesa         enable canvas with software OpenGL implementation (Mesa)
-  --with-nogui            do not use GUI toolkit (not maintained)
   --with-wxdebug          compiles wxWidgets with debuging options
   --with-wxsrcdir=...     compiles Amaya with a specific wxWidgets sources path
   --with-graphiclibs      use static libjpeg, libpng.
@@ -13399,7 +13405,7 @@ if test "${with_gtk+set}" = set; then
   withval="$with_gtk"
 
 fi;
-if test "$with_gtk" = "yes" -o "$enable_gtk" = "yes" ; then
+if test "$with_gtk" = "yes" ; then
   if test "$withval" = "no" ; then
     with_gtk="no"
     with_wx="yes"
@@ -13416,7 +13422,7 @@ if test "${with_wx+set}" = set; then
   withval="$with_wx"
 
 fi;
-if test "$with_wx" = "yes" -o "$enable_wx" = "yes" ; then
+if test "$with_wx" = "yes" ; then
   if test "$withval" = "no" ; then
     with_wx="no"
   else
@@ -13443,12 +13449,7 @@ if test "${with_MESA+set}" = set; then
 
 fi;
 if test "$with_mesa" = "" ; then
- if test "$enable_mesa" = "yes" ; then
-    with_mesa="yes"
-    with_gl="no"
-  else
-    with_mesa="no"
-  fi
+  with_mesa="no"
 fi
 
 
@@ -13471,20 +13472,6 @@ if test "$with_wx" = "yes" -o "$with_wx" = "" ; then
     with_mesa="yes"
   fi
  fi
-fi
-
-# check if no gui is enable
-
-# Check whether --with-nogui or --without-nogui was given.
-if test "${with_nogui+set}" = set; then
-  withval="$with_nogui"
-
-fi;
-if test "$with_nogui" = "yes" -o "$enable_nogui" = "yes" ; then
-  with_nogui="yes"
-  with_gtk="no"
-  with_wx="no"
-  NOGUI_OPTIONS="-D_NOGUI"
 fi
 
 # check if wxWidgets debug is enable
@@ -14620,96 +14607,118 @@ if test "${enable_generic_xml+set}" = set; then
 
 fi;
 
-
-if test "$with_plugin" = "" ; then
-  if test "$enable_plugin" = "yes" ; then
-    with_plugin="yes"
-  else
-    with_plugin="no"
-  fi
-fi
-
-if test "$with_svg" = "" ; then
-    if test "$enable_svg" = "no" ; then
-	with_svg="no"
-    else
-	with_svg="yes"
-    fi
-fi
-
-if test "$with_annot" = "" ; then
-    if test "$enable_annot" = "no" ; then
-	with_annot="no"
-    else
-	with_annot="yes"
-    fi
+# Check whether --enable-svg or --disable-svg was given.
+if test "${enable_svg+set}" = set; then
+  enableval="$enable_svg"
+  case "${enableval}" in
+	  yes) with_svg="yes" ;;
+	  no)  with_svg="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-svg" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-svg" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
 else
-    with_annot="yes"
-fi
+  with_svg="yes"
+fi;
 
-
-if test "$with_redland" = "" ; then
-    if test "$enable_redland" = "no" ; then
-	with_redland="no"
-    else
-	with_redland="yes"
-    fi
+# Check whether --enable-annot or --disable-annot was given.
+if test "${enable_annot+set}" = set; then
+  enableval="$enable_annot"
+  case "${enableval}" in
+	  yes) with_annot="yes" ;;
+	  no)  with_annot="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-annot" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-annot" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
 else
-    with_redland="yes"
-fi
+  with_annot="yes"
+fi;
 
-if test "$with_system_redland" = "" ; then
-    if test "$enable_system_redland" = "yes" ; then
-	with_redland="yes"
-	with_system_redland="yes"
-    else
-	with_system_redland="no"
-    fi
+# Check whether --enable-redland or --disable-redland was given.
+if test "${enable_redland+set}" = set; then
+  enableval="$enable_redland"
+  case "${enableval}" in
+	  yes) with_redland="yes" ;;
+	  no)  with_redland="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-redland" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-redland" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
 else
-    with_system_redland="no"
-fi
+  with_redland="yes"
+fi;
 
-if test "$with_bookmarks" = "" ; then
-    if test "$enable_bookmarks" = "yes" ; then
-	with_bookmarks="yes"
-	with_redland="yes"
-    else
-	with_bookmarks="no"
-    fi
+# Check whether --enable-bookmarks or --disable-bookmarks was given.
+if test "${enable_bookmarks+set}" = set; then
+  enableval="$enable_bookmarks"
+  case "${enableval}" in
+	  yes) with_bookmarks="yes"; with_redland="yes" ;;
+	  no)  with_bookmarks="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-bookmarks" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-bookmarks" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
 else
-    with_bookmarks="no"
-fi
+  with_bookmarks="no"
+fi;
 
-if test "$with_templates" = "no " -o "$enable_templates" = "no"; then
-      with_templates="no"
+# Check whether --enable-templates or --disable-templates was given.
+if test "${enable_templates+set}" = set; then
+  enableval="$enable_templates"
+  case "${enableval}" in
+	  yes) with_templates="yes" ;;
+	  no)  with_templates="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-templates" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-templates" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
 else
-  if test "$with_wx" = "no"; then
-      { echo "$as_me:$LINENO: WARNING: Templates are only available in WX version !!" >&5
+  with_templates="yes"
+fi;
+
+if test "$with_templates" = yes -a "$with_wx" != "yes"; then
+    { echo "$as_me:$LINENO: WARNING: Templates are only available in WX version !!" >&5
 echo "$as_me: WARNING: Templates are only available in WX version !!" >&2;}
-      { echo "$as_me:$LINENO: WARNING: Disabling templates" >&5
+    { echo "$as_me:$LINENO: WARNING: Disabling templates" >&5
 echo "$as_me: WARNING: Disabling templates" >&2;}
-      with_templates="no"
-   else
-      with_templates="yes"
-   fi
+    with_templates="no"
 fi
 
-if test "$with_templates" = "yes" -o "$with_templates" = "" ; then
+if test "$with_templates" = "yes" ; then
     TEMPLATES_OPTIONS="-DTEMPLATES"
 else
     TEMPLATES_OPTIONS=""
 fi
 
 
-if test "$with_generic_xml" = "" ; then
-    if test "$enable_generic_xml" = "no" ; then
-	    with_generic_xml="no"
-	    GENERIC_XML_OPTIONS=
-    else
-	    with_generic_xml="yes"
-	    GENERIC_XML_OPTIONS=-DXML_GENERIC
-    fi
-fi
+# Check whether --enable-generic-xml or --disable-generic-xml was given.
+if test "${enable_generic_xml+set}" = set; then
+  enableval="$enable_generic_xml"
+  case "${enableval}" in
+	  yes) with_generic_xml="yes" ;;
+	  no)  with_generic_xml="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-generic-xml" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-generic-xml" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
+else
+  with_generic_xml="yes"
+fi;
+
+# Check whether --enable-system-redland or --disable-system-redland was given.
+if test "${enable_system_redland+set}" = set; then
+  enableval="$enable_system_redland"
+  case "${enableval}" in
+	  yes) with_system_redland="yes"; with_redland="yes" ;;
+	  no)  with_system_redland="no" ;;
+	  *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-system-redland" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-system-redland" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
+else
+  with_system_redland="no"
+fi;
 
 
 # Check whether --with-dav or --without-dav was given.
@@ -14873,15 +14882,6 @@ echo "$as_me: WARNING: Disabling bookmarks build as redland is disabled !" >&2;}
     	ANNOTLIB_COMPILE_BM='#'
     fi
 
-    if test "$with_plugin" = "yes" ; then
-        { echo "$as_me:$LINENO: WARNING: The plugin library isn't supported anymore in Amaya !!" >&5
-echo "$as_me: WARNING: The plugin library isn't supported anymore in Amaya !!" >&2;}
-        { echo "$as_me:$LINENO: WARNING: Disabling plugin build !" >&5
-echo "$as_me: WARNING: Disabling plugin build !" >&2;}
-        with_plugin="no"
-    fi
-
-
     if test ! -f $srcdir/davlib/Makefile.in ; then
 	if test "$with_dav" = "yes" ; then
 	    { echo "$as_me:$LINENO: WARNING: WebDAV makefile not found !!" >&5
@@ -14906,7 +14906,6 @@ if test "$with_debug" = "yes" ; then
 else
   AMAYA_OPTIONS="$OS_OPTIONS $MATH_OPTIONS $SVG_OPTIONS $GENERIC_XML_OPTIONS $GTK_OPTIONS $GL_OPTIONS $WX_OPTIONS $NOGUI_OPTIONS $TEMPLATES_OPTIONS"
 fi
-#PLUGIN_OPTIONS="-DPLUGIN_TRACE -DXP_UNIX"
 AMAYA_ANNOT_OPTIONS="$OS_OPTIONS $AMAYA_ANNOT_OPTIONS"
 
 if test "$with_wx" = "yes" ; then
@@ -15008,15 +15007,6 @@ AMAYA_INSTALLDIR="Amaya-${APP_VER}"
 
 
 
-if test "$with_plugin" = "yes" ; then
-
-    plugin_frag=$srcdir/pluginlib/Makefile.plugin
-else
-
-    plugin_frag=/dev/null
-fi
-
-
     www_frag=$srcdir/amaya/Makefile.libwww
 
 if test "$with_math" = "no" ; then
@@ -15073,15 +15063,9 @@ make_output="Makefile Options.orig:Options.in tools/Makefile \
 
 if test "$build_amaya" = "yes" ; then
 
-    make_output="$make_output amaya/Makefile pluginlib/Makefile"
+    make_output="$make_output amaya/Makefile"
     EXTRA_MAKEFILE_IN="$srcdir/amaya/Makefile.in \
     $srcdir/amaya/Makefile.libwww"
-
-    if test "$with_plugin" = "yes" ; then
-       make_output="$make_output pluginlib/Makefile"
-       EXTRA_MAKEFILE_IN="$srcdir/pluginlib/Makefile.in \
-       $srcdir/pluginlib/Makefile.plugin"
-    fi
 
     if test "$with_annot" = "yes" ; then
        make_output="$make_output annotlib/Makefile"
@@ -15807,7 +15791,6 @@ s,@VPATHOPT@,$VPATHOPT,;t t
 s,@GTK_OPTIONS@,$GTK_OPTIONS,;t t
 s,@THOT_OPTIONS@,$THOT_OPTIONS,;t t
 s,@AMAYA_OPTIONS@,$AMAYA_OPTIONS,;t t
-s,@PLUGIN_OPTIONS@,$PLUGIN_OPTIONS,;t t
 s,@AMAYA_ANNOT_OPTIONS@,$AMAYA_ANNOT_OPTIONS,;t t
 s,@AMAYA_ANNOT_INCLUDES@,$AMAYA_ANNOT_INCLUDES,;t t
 s,@AMAYA_ANNOT_EXTRA_LIBS@,$AMAYA_ANNOT_EXTRA_LIBS,;t t
@@ -15829,8 +15812,6 @@ s,@LIBWWW_RDF_PARSER@,$LIBWWW_RDF_PARSER,;t t
 s,@SUBDIRS@,$SUBDIRS,;t t
 s,@EXTRA_MAKEFILE_IN@,$EXTRA_MAKEFILE_IN,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
-/@plugin_frag@/r $plugin_frag
-s,@plugin_frag@,,;t t
 /@www_frag@/r $www_frag
 s,@www_frag@,,;t t
 /@math_frag@/r $math_frag
@@ -16483,9 +16464,6 @@ fi
 if test "$build_amaya" = "yes" ; then
     echo Amaya $AMAYA_VER configured
     echo Amaya configured with libWWW
-    if test "$with_plugin" = "yes" ; then
-        echo Amaya configured with Plugins support
-    fi
     if test "$with_math" = "yes" ; then
 	echo Amaya configured with Math support
     fi
