Irene

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6092,7 +6092,6 @@ fi
 THOT_VER="2.2"
 AMAYA_VER="1.3"
 KAFFE_VER="snap"
-LIBWWW_VER="5.1m"
 
 CEXTRACT_VER="1.7"
 CEXTRACT_FLAGS="+O"
@@ -6305,7 +6304,7 @@ if test "$with_ilu" = "yes" ; then
                 # Extract the first word of "c-stubber", so it can be a program name with args.
 set dummy c-stubber; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:6309: checking for $ac_word" >&5
+echo "configure:6308: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CSTUBBER'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -6406,9 +6405,9 @@ if test "$build_amaya" = "yes" ; then
 	fi
     fi
 
-    if test ! -f $srcdir/w3c-libwww-$LIBWWW_VER/Makefile.in ; then
+    if test ! -f $srcdir/libwww/Makefile.in ; then
 	if test "$with_java" = "no" -a "$with_ilu" = "no" ; then
-	    echo "configure: warning: w3c-libwww-$LIBWWW_VER sources not found !!" 1>&2
+	    echo "configure: warning: libwww sources not found !!" 1>&2
 	    echo "configure: warning: Disabling Amaya build !" 1>&2
 	    build_amaya="no"
 	fi
@@ -6467,7 +6466,6 @@ APIINCLUDES=-I$API
 if test "$VPATHOPT" = "" ; then
 	VPATHOPT="VPATH"
 fi
-
 
 
 
@@ -6825,7 +6823,6 @@ s%@MOTIF_LIBRARIES@%$MOTIF_LIBRARIES%g
 s%@CSTUBBER@%$CSTUBBER%g
 s%@THOT_VER@%$THOT_VER%g
 s%@AMAYA_VER@%$AMAYA_VER%g
-s%@LIBWWW_VER@%$LIBWWW_VER%g
 s%@KAFFE_VER@%$KAFFE_VER%g
 s%@CEXTRACT_VER@%$CEXTRACT_VER%g
 s%@CEXTRACT_FLAGS@%$CEXTRACT_FLAGS%g
