GL : Added Freetype linking for opengl fonts

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6499,9 +6499,15 @@ echo "configure:6492: checking OpenGL" >&5
 		; \
 	do  if test -r "$ac_dir/gl.h" ; then
                 gl_inc="yes"
+		GL_INC_I="$ac_dir"
+		if test "$ac_dir" != "/usr/include" ; then
+		   GL_INCLUDES="-I$ac_dir"
+		fi
        	 	break	
     	    fi
-	done		
+	done	
+  	echo $ac_n "checking GLU""... $ac_c" 1>&6
+echo "configure:6511: checking GLU" >&5	
 	for ac_dir in               		\
 		/usr/include/GL			\
 		/usr/include 			\
@@ -6512,9 +6518,17 @@ echo "configure:6492: checking OpenGL" >&5
 		; \
 	do  if test -r "$ac_dir/glu.h" ; then
                 glu_inc="yes"
+		GL_INC_II="$ac_dir"
+		if test "$ac_dir" != "/usr/include" ; then
+			if test "$ac_dir" != "$GL_INC_I" ; then
+		   	    GL_INCLUDES="$GL_INCLUDES -I$ac_dir"
+			fi
+		fi
        	 	break	
     	    fi
 	done	
+  	echo $ac_n "checking GTKGLAREA""... $ac_c" 1>&6
+echo "configure:6532: checking GTKGLAREA" >&5	
 	for ac_dir in               		\
 		/usr/include/GL			\
 		/usr/include 			\
@@ -6525,9 +6539,29 @@ echo "configure:6492: checking OpenGL" >&5
 		; \
 	do  if test -r "$ac_dir/gtkgl/gtkglarea.h" ; then
                 gtkgl_inc="yes"
+		if test "$ac_dir" != "/usr/include" ; then
+			if test "$ac_dir" != "$GL_INC_II" ; then
+				if test "$ac_dir" != "$GL_INC_I" ; then
+		   			GL_INCLUDES="$GL_INCLUDES -I$ac_dir"
+				fi
+			fi
+		fi
        	 	break	
     	    fi
 	done	
+  	echo $ac_n "checking freetype""... $ac_c" 1>&6
+echo "configure:6554: checking freetype" >&5	
+	for ac_dir in               		\
+		/usr/include 			\
+		/usr/X11R6/include 		\
+		/usr/local/include		\
+		; \
+	do  if test -r "$ac_dir/ft2build.h" ; then
+                freetype_inc="yes"
+		GL_INCLUDES="$GL_INCLUDES `freetype-config --cflags`"
+       	 	break	
+    	    fi
+	done		
 	if test "$gl_inc" = "" ; then
 	 	echo "configure: warning: Opengl headers (gl.h) not found !!" 1>&2
 	   	echo "configure: warning: Disabling opengl build !" 1>&2
@@ -6552,13 +6586,22 @@ echo "configure:6492: checking OpenGL" >&5
 	        GL_INCLUDES=	
 		GL_LIBRARIES=
 	fi
+	if test "$freetype_inc" = "" ; then
+	 	echo "configure: warning: Freetype 2 headers (ft2build.h) not found !!" 1>&2
+	   	echo "configure: warning: Disabling opengl build !" 1>&2
+	   	with_gl="no"
+	    	GL_OPTIONS=	
+	        GL_INCLUDES=
+		GL_LIBRARIES=
+	fi
 	if test "$gl_inc" = "yes" ; then
 		if test "$glu_inc" = "yes" ; then
 			if test "$gtkgl_inc" = "yes" ; then
-				GL_INCLUDES="-I$ac_dir "
-				GL_LIBRARIES=" -lXmu -lXft -lGL -lGLU -lgtkgl "
+	                    if test "$freetype_inc" = "yes" ; then	
+				GL_LIBRARIES=" -lXmu -lXft -lfreetype -lGL -lGLU -lgtkgl "
 				GL_OPTIONS=-D_GL 
 	  			no_motif=yes
+			    fi
 			fi
 		fi
 	fi
