Enable --enable-system-wx configure option (works on ubuntu-8.04).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13470,10 +13470,21 @@ esac
 
 
 with_wx="yes"
+
 # Check whether --enable-system-wx was given.
 if test "${enable_system_wx+set}" = set; then
-  enableval=$enable_system_wx;
+  enableval=$enable_system_wx; case "${enableval}" in
+      yes) with_system_wx="yes";;
+      no)  with_system_wx="no" ;;
+      *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-system-wx" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-system-wx" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+  with_system_wx="no"
 fi
+
+
 
 
 
@@ -13571,7 +13582,7 @@ if test "$with_mesa" = "yes" ; then
 
 fi
 
-if test "$enable_system_wx" = "yes"; then
+if test "$with_system_wx" = "yes"; then
   # Extract the first word of "wx-config", so it can be a program name with args.
 set dummy wx-config; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -13613,11 +13624,11 @@ fi
 
 
   if test -z "$WXCONFIG"; then
-    enable_system_wx="no"
+    with_system_wx="no"
   fi
 fi
 
-if test "$enable_system_wx" != "yes"; then
+if test "$with_system_wx" != "yes"; then
   # WX_SRCDIR is better to understand the code than with_wxsrcdir variable
   if test ! -f $with_wxsrcdir/Makefile.in ; then
     $with_wxsrcdir = ../../wxWidgets
@@ -13718,7 +13729,7 @@ echo "$as_me: error: Cannot find wx-config. Please download wxWidgets (http://ww
   BUILDWXWIDGETS="wxwidgets"
 
 
-fi #!$enable_system_wx
+fi #!$with_system_wx
 
 WX_INCLUDES="$WX_INCLUDES `$WXCONFIG --cxxflags`"
 
@@ -14690,10 +14701,6 @@ if test "$build_amaya" = "yes" ; then
     if test "$with_dav" = "yes" ; then
        make_output="$make_output davlib/Makefile"
        EXTRA_MAKEFILE_IN="$srcdir/davlib/Makefile.in"
-    fi
-
-    if test "$with_wx" = "yes" -a "enable_system_wx" = "yes" ; then
-       EXTRA_MAKEFILE_IN="$EXTRA_MAKEFILE_IN $WX_SRCDIR/Makefile.in $WX_SRCDIR/configure.in"
     fi
 
 fi
