JK: New options for compiling the raptor RDF parser with Amaya. You'll need to do a ../configure --with-raptor to enable it for the moment. It'll become the standard one after some testing.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26,9 +26,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --disable-annot         remove Annotations support "
 ac_help="$ac_help
-  --disable-generic-xml   remove Generic XML support "
+  --disable-raptor        disable the raptor RDF parser "
 ac_help="$ac_help
-  --disable-annot-threads remove annotation threads "
+  --disable-generic-xml   remove Generic XML support "
 ac_help="$ac_help
   --with-dav             enable WebDAV support (experimental) "
 
@@ -960,7 +960,7 @@ if test "$ac_test_CFLAGS" = set; then
   CFLAGS="$ac_save_CFLAGS"
 elif test $ac_cv_prog_cc_g = yes; then
   if test "$GCC" = yes; then
-    CFLAGS="-O2"
+    CFLAGS="-g"
   else
     CFLAGS="-g"
   fi
@@ -4903,7 +4903,7 @@ else
 int main() {
 
 /* Ultrix mips cc rejects this.  */
-typedef int charset[2]; const charset x = {0,0};
+typedef int charset[2]; const charset x;
 /* SunOS 4.1.1 cc rejects this.  */
 char const *const *ccp;
 char **p;
@@ -4978,7 +4978,7 @@ for ac_kw in inline __inline__ __inline; do
 #include "confdefs.h"
 
 int main() {
-} int $ac_kw foo() {
+} $ac_kw foo() {
 ; return 0; }
 EOF
 if { (eval echo configure:4985: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
@@ -5292,7 +5292,7 @@ else
 #include "confdefs.h"
 #include <alloca.h>
 int main() {
-void *p = alloca(2 * sizeof(int));
+char *p = alloca(2 * sizeof(int));
 ; return 0; }
 EOF
 if { (eval echo configure:5299: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
@@ -5799,15 +5799,12 @@ else
 #include <sys/types.h>
 #include <fcntl.h>
 #include <sys/mman.h>
-#include <stdlib.h>
-#include <sys/stat.h>
-
-#ifdef HAVE_UNISTD_H
-# include <unistd.h>
-#endif
 
 /* This mess was copied from the GNU getpagesize.h.  */
 #ifndef HAVE_GETPAGESIZE
+# ifdef HAVE_UNISTD_H
+#  include <unistd.h>
+# endif
 
 /* Assume that all systems that can run configure have sys/param.h.  */
 # ifndef HAVE_SYS_PARAM_H
@@ -5862,7 +5859,7 @@ main()
 	/*
 	 * First, make a file with some known garbage in it.
 	 */
-	data = (char*)malloc(pagesize);
+	data = malloc(pagesize);
 	if (!data)
 		exit(1);
 	for (i = 0; i < pagesize; ++i)
@@ -5883,7 +5880,7 @@ main()
 	fd = open("conftestmmap", O_RDWR);
 	if (fd < 0)
 		exit(1);
-	data2 = (char*)malloc(2 * pagesize);
+	data2 = malloc(2 * pagesize);
 	if (!data2)
 		exit(1);
 	data2 += (pagesize - ((int) data2 & (pagesize - 1))) & (pagesize - 1);
@@ -5901,7 +5898,7 @@ main()
 	 */
 	for (i = 0; i < pagesize; ++i)
 		*(data2 + i) = *(data2 + i) + 1;
-	data3 = (char*)malloc(pagesize);
+	data3 = malloc(pagesize);
 	if (!data3)
 		exit(1);
 	if (read(fd, data3, pagesize) != pagesize)
@@ -5915,7 +5912,7 @@ main()
 }
 
 EOF
-if { (eval echo configure:5919: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:5916: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_func_mmap_fixed_mapped=yes
 else
@@ -5938,12 +5935,12 @@ EOF
 fi
 
 echo $ac_n "checking return type of signal handlers""... $ac_c" 1>&6
-echo "configure:5942: checking return type of signal handlers" >&5
+echo "configure:5939: checking return type of signal handlers" >&5
 if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 5947 "configure"
+#line 5944 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -5960,7 +5957,7 @@ int main() {
 int i;
 ; return 0; }
 EOF
-if { (eval echo configure:5964: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:5961: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_type_signal=void
 else
@@ -5979,12 +5976,12 @@ EOF
 
 
 echo $ac_n "checking for vprintf""... $ac_c" 1>&6
-echo "configure:5983: checking for vprintf" >&5
+echo "configure:5980: checking for vprintf" >&5
 if eval "test \"`echo '$''{'ac_cv_func_vprintf'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 5988 "configure"
+#line 5985 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char vprintf(); below.  */
@@ -6007,7 +6004,7 @@ vprintf();
 
 ; return 0; }
 EOF
-if { (eval echo configure:6011: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:6008: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_vprintf=yes"
 else
@@ -6031,12 +6028,12 @@ fi
 
 if test "$ac_cv_func_vprintf" != yes; then
 echo $ac_n "checking for _doprnt""... $ac_c" 1>&6
-echo "configure:6035: checking for _doprnt" >&5
+echo "configure:6032: checking for _doprnt" >&5
 if eval "test \"`echo '$''{'ac_cv_func__doprnt'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 6040 "configure"
+#line 6037 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char _doprnt(); below.  */
@@ -6059,7 +6056,7 @@ _doprnt();
 
 ; return 0; }
 EOF
-if { (eval echo configure:6063: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:6060: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func__doprnt=yes"
 else
@@ -6086,12 +6083,12 @@ fi
 for ac_func in getcwd gethostname gettimeofday getwd mkdir mktime putenv select socket strdup strerror strftime strstr strtod strtol uname lstat strcasecmp strncasecmp strchr memcpy
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:6090: checking for $ac_func" >&5
+echo "configure:6087: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 6095 "configure"
+#line 6092 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -6114,7 +6111,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:6118: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:6115: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -6218,7 +6215,7 @@ motif_includes=NONE
 motif_libraries=NONE
 
 echo $ac_n "checking for Motif""... $ac_c" 1>&6
-echo "configure:6222: checking for Motif" >&5
+echo "configure:6219: checking for Motif" >&5
 if test "x$motif_includes" != xNONE && test "x$motif_libraries" != xNONE; then
     no_motif=
 else
@@ -6393,9 +6390,9 @@ fi
 
 if test "$no_graphic" = yes; then
     echo $ac_n "checking for libjpeg version = 6b""... $ac_c" 1>&6
-echo "configure:6397: checking for libjpeg version = 6b" >&5
+echo "configure:6394: checking for libjpeg version = 6b" >&5
     cat > conftest.$ac_ext <<EOF
-#line 6399 "configure"
+#line 6396 "configure"
 #include "confdefs.h"
 #include <jpeglib.h>
          x JPEG_LIB_VERSION x
@@ -6414,9 +6411,9 @@ fi
 rm -f conftest*
 
     echo $ac_n "checking for libpng version = 1.0.x""... $ac_c" 1>&6
-echo "configure:6418: checking for libpng version = 1.0.x" >&5
+echo "configure:6415: checking for libpng version = 1.0.x" >&5
     cat > conftest.$ac_ext <<EOF
-#line 6420 "configure"
+#line 6417 "configure"
 #include "confdefs.h"
 #include <png.h>
 	x PNG_LIBPNG_VER_STRING x
@@ -6480,6 +6477,7 @@ else
   fi
 fi
 
+
 # Check whether --with-i18n or --without-i18n was given.
 if test "${with_i18n+set}" = set; then
   withval="$with_i18n"
@@ -6504,7 +6502,7 @@ fi
 
 if test "$with_gl" = "yes" ; then
   	echo $ac_n "checking OpenGL""... $ac_c" 1>&6
-echo "configure:6508: checking OpenGL" >&5
+echo "configure:6506: checking OpenGL" >&5
 	for ac_dir in               		\
 		/usr/include 			\
 		/usr/X11R6/include 		\
@@ -6520,7 +6518,7 @@ echo "configure:6508: checking OpenGL" >&5
     	    fi
 	done	
   	echo $ac_n "checking GLU""... $ac_c" 1>&6
-echo "configure:6524: checking GLU" >&5	
+echo "configure:6522: checking GLU" >&5	
 	for ac_dir in               		\
 		/usr/include/GL			\
 		/usr/include 			\
@@ -6541,7 +6539,7 @@ echo "configure:6524: checking GLU" >&5
     	    fi
 	done	
   	echo $ac_n "checking GTKGLAREA""... $ac_c" 1>&6
-echo "configure:6545: checking GTKGLAREA" >&5	
+echo "configure:6543: checking GTKGLAREA" >&5	
 	for ac_dir in               		\
 		/usr/include/GL			\
 		/usr/include 			\
@@ -6563,7 +6561,7 @@ echo "configure:6545: checking GTKGLAREA" >&5
     	    fi
 	done	
   	echo $ac_n "checking freetype""... $ac_c" 1>&6
-echo "configure:6567: checking freetype" >&5	
+echo "configure:6565: checking freetype" >&5	
 	for ac_dir in               		\
 		/usr/include 			\
 		/usr/X11R6/include 		\
@@ -6639,15 +6637,15 @@ if test "${enable_annot+set}" = set; then
   :
 fi
 
-# Check whether --enable-generic-xml or --disable-generic-xml was given.
-if test "${enable_generic_xml+set}" = set; then
-  enableval="$enable_generic_xml"
+# Check whether --enable-raptor or --disable-raptor was given.
+if test "${enable_raptor+set}" = set; then
+  enableval="$enable_raptor"
   :
 fi
 
-# Check whether --enable-annot-threads or --disable-annot-threads was given.
-if test "${enable_annot_threads+set}" = set; then
-  enableval="$enable_annot_threads"
+# Check whether --enable-generic-xml or --disable-generic-xml was given.
+if test "${enable_generic_xml+set}" = set; then
+  enableval="$enable_generic_xml"
   :
 fi
 
@@ -6677,6 +6675,15 @@ if test "$with_annot" = "" ; then
     fi
 fi
 
+
+if test "$with_raptor" = "" ; then
+    if test "$enable_raptor" = "no" ; then
+	with_raptor="no"
+    else
+	with_raptor"yes"
+    fi
+fi
+
 if test "$with_generic_xml" = "" ; then
     if test "$enable_generic_xml" = "no" ; then
 	with_generic_xml="no"
@@ -6684,16 +6691,6 @@ if test "$with_generic_xml" = "" ; then
     else
 	with_generic_xml="yes"
 	GENERIC_XML_OPTIONS=-DXML_GENERIC
-    fi
-fi
-
-if test "$with_annot_threads" = "" ; then
-    if test "$enable_annot_threads" = "no" ; then
-	with_annot_threads="no"
-	ANNOT_THREAD_OPTIONS=
-    else
-	with_annot_threads="yes"
-	ANNOT_THREAD_OPTIONS=
     fi
 fi
 
@@ -6760,6 +6757,31 @@ if test "$build_amaya" = "yes" ; then
 	fi
     fi
 
+    if test "$with_annot" = "yes" -a "$with_raptor" = "yes" ; then
+       if test ! -d "$srcdir/libraptor" ; then
+          echo "configure: warning: Raptor source dir not found !!" 1>&2
+	  echo "configure: warning: Disabling raptor build !" 1>&2
+	  MAKERAPTOR='#'
+	  with_raptor="no"
+       else
+	   AMAYA_ANNOT_OPTIONS="$AMAYA_ANNOT_OPTIONS -DRAPTOR_RDF_PARSER -I\$(THOTDIR)/libraptor"
+ 	   AMAYA_RAPTOR_LIBS="-L../libraptor/.libs -lraptor"
+	   AMAYA_RAPTOR_SRC="amaya_comp_libraptor"
+	   AMAYA_RAPTOR_INCLUDES="-I\$(THOTDIR)/libraptor"
+       fi
+    else
+       echo "configure: warning: Disabling raptor build as annotations are disabled !" 1>&2
+       MAKERAPTOR='#'
+       with_raptor="no"
+    fi
+
+        if test "$with_raptor" = "yes" ; then
+                     MAKE_LIBWWW_RDF_PARSER="libwwwxml"
+       LIBWWW_RDF_PARSER="-lwwwxml"
+                  else
+       MAKE_LIBWWW_RDF_PARSER="libwwwxml"
+       LIBWWW_RDF_PARSER="-lwwwxml"
+    fi
 
     if test "$with_plugin" = "yes" ; then
         echo "configure: warning: The plugin library isn't supported anymore in Amaya !!" 1>&2
@@ -6785,9 +6807,9 @@ fi
 
 
 THOT_OPTIONS="$GTK_OPTIONS $I18N_OPTIONS $GL_OPTIONS"
-AMAYA_OPTIONS="$MATH_OPTIONS $SVG_OPTIONS $GTK_OPTIONS $GENERIC_XML_OPTIONS $I18N_OPTIONS $ANNOT_THREAD_OPTIONS $GL_OPTIONS"
+AMAYA_OPTIONS="$MATH_OPTIONS $SVG_OPTIONS $GTK_OPTIONS $GENERIC_XML_OPTIONS $I18N_OPTIONS $GL_OPTIONS"
 #PLUGIN_OPTIONS="-DPLUGIN_TRACE -DXP_UNIX"
-AMAYA_ANNOT_OPTIONS="$I18N_OPTIONS $ANNOT_THREAD_OPTIONS"
+AMAYA_ANNOT_OPTIONS="$AMAYA_ANNOT_OPTIONS $I18N_OPTIONS"
 IMGLIBS="-ljpeg -lpng -lz"
 EXTRA_LIBS=
 
@@ -6812,6 +6834,15 @@ APIINCLUDES=-I${API}
 if test "${VPATHOPT}" = "" ; then
 	VPATHOPT="VPATH"
 fi
+
+
+
+
+
+
+
+
+
 
 
 
@@ -6874,9 +6905,6 @@ fi
 if test "$with_dav" = "yes" ; then
     
     dav_frag=$srcdir/davlib/Makefile.dav
-else
-    
-    dav_frag=/dev/null
 fi
 
 
@@ -6891,12 +6919,12 @@ if test "$build_amaya" = "yes" ; then
 
     make_output="$make_output amaya/Makefile pluginlib/Makefile"
     EXTRA_MAKEFILE_IN="$srcdir/amaya/Makefile.in \
-$srcdir/amaya/Makefile.libwww"
+    $srcdir/amaya/Makefile.libwww"
 
     if test "$$with_plugin" = "yes" ; then
        make_output="$make_output pluginlib/Makefile"
        EXTRA_MAKEFILE_IN="$srcdir/pluginlib/Makefile.in \
-$srcdir/pluginlib/Makefile.plugin"
+       $srcdir/pluginlib/Makefile.plugin"
     fi
 
     if test "$with_annot" = "yes" ; then
@@ -7116,6 +7144,13 @@ s%@DAVDIR@%$DAVDIR%g
 s%@LIBDAV@%$LIBDAV%g
 s%@WITHDAV@%$WITHDAV%g
 s%@WWWDAV@%$WWWDAV%g
+s%@MAKERAPTOR@%$MAKERAPTOR%g
+s%@AMAYA_RAPTOR_LIBS@%$AMAYA_RAPTOR_LIBS%g
+s%@AMAYA_RAPTOR_SRC@%$AMAYA_RAPTOR_SRC%g
+s%@AMAYA_RAPTOR_INCLUDES@%$AMAYA_RAPTOR_INCLUDES%g
+s%@MAKE_LIBWWW_RDF_PARSER@%$MAKE_LIBWWW_RDF_PARSER%g
+s%@LIBWWW_RDF_PARSER@%$LIBWWW_RDF_PARSER%g
+s%@SUBDIRS@%$SUBDIRS%g
 /@plugin_frag@/r $plugin_frag
 s%@plugin_frag@%%g
 /@www_frag@/r $www_frag
@@ -7377,6 +7412,9 @@ if test "$build_amaya" = "yes" ; then
     fi
     if test "$with_annot" = "yes" ; then
 	echo Amaya configured with Annotations support
+    fi
+    if test "$with_raptor" = "yes" ; then
+	echo Amaya configured to use the raptor RDF parser
     fi
     if test "$with_generic_xml" = "yes" ; then
 	echo Amaya configured with generic XML suppport
