fix a link problem (wxWidgets version) : now wxWidgets and Mesa libraries are linked staticaly into Amaya binary. Notice : remove your old 'Option' file or merge it with the new generated 'Option.orig'. S. GULLY

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13579,18 +13579,26 @@ echo "$as_me: error: Mesa library sources not found (opengl). Please download Me
   echo "---> Compiling Mesa library."
   if test "$OS_OPTIONS" = "-D_UNIX" ; then
     # LINUX
-    make linux
+    # compile only .a libraries because Amaya is linked staticaly with mesa
+    make linux-static
+    if test $? != 0 ; then
+      { { echo "$as_me:$LINENO: error: A problem occurs durring Mesa library compilation. Please fix the problem and try again." >&5
+echo "$as_me: error: A problem occurs durring Mesa library compilation. Please fix the problem and try again." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
   fi
   echo "---> Compiling Mesa library. - DONE"
 
 
-  echo "---> Install Mesa library into Amaya."
+  echo "---> Install Mesa library into Amaya/Mesa/"
   mkdir -p $OLDDIR/../Mesa
   mkdir -p $OLDDIR/../Mesa/include
   mkdir -p $OLDDIR/../Mesa/lib
+  # copy includes
   cp -r include/GL $OLDDIR/../Mesa/include/
-  cp -r lib/* $OLDDIR/../Mesa/lib/
-  echo "---> Install Mesa library into Amaya. - DONE"
+  # copy libraries (only .a because we dont want to share)
+  cp lib/*.a $OLDDIR/../Mesa/lib/
+  echo "---> Install Mesa library into Amaya/Mesa/ - DONE"
 
 
   cd $OLDDIR
@@ -13625,13 +13633,20 @@ echo "$as_me: error: wxWidgets library sources not found. Please download wxWidg
   # setup configure options
   if test "$OS_OPTIONS" = "-D_UNIX" ; then
     # LINUX
-    WXCONFIGURE_OPTION="--with-opengl --with-gtk --enable-gtk2 --enable-unicode"
+    #   --enable-gtk2           use GTK+ 2.0 if available (EXPERIMENTAL)
+    #   --enable-shared         create shared library code
+    #   --enable-unicode        compile wxString with Unicode support
+    #   --with-gtk              use GTK+
+    #   --with-opengl           use OpenGL (or Mesa)
+    WXCONFIGURE_OPTION="--with-opengl --with-gtk --enable-gtk2 --enable-unicode --enable-shared=no"
   fi
   if test "$OS_OPTIONS" = "-D_UNIX -D_MACOS" ; then
     # MACOSX
     { { echo "$as_me:$LINENO: error: TODO: configurer wxWidgets pour MACOSX" >&5
 echo "$as_me: error: TODO: configurer wxWidgets pour MACOSX" >&2;}
    { (exit 1); exit 1; }; }
+    # --with-mac              use Mac OS X
+    # --with-cocoa            use Cocoa
     # WXCONFIGURE_OPTION="--with-opengl --with-gtk --enable-gtk2 --enable-unicode"
   fi
   if test $with_wxdebug = yes ; then
@@ -13639,12 +13654,19 @@ echo "$as_me: error: TODO: configurer wxWidgets pour MACOSX" >&2;}
     # SG: I've disabled other debug options because the lib has bugs when using these flags \
     # (maybe because these flags are not often used by wxWidgets developpers)
     # WXCONFIGURE_OPTION="$WXCONFIGURE_OPTION --enable-debug --enable-debug_cntxt --enable-debug_gdb --enable-debug_info --enable-debug_flag --enable-mem_tracing"
+  else
+    WXCONFIGURE_OPTION="$WXCONFIGURE_OPTION --enable-optimise"
   fi
 
   # launch the configure
   if test "$with_mesa" = "yes" ; then
     # use internal OpenGL (mesa) libraries
     ../configure CFLAGS="-I../../Mesa/include" CXXFLAGS="-I../../Mesa/include" CPPFLAGS="-I../../Mesa/include" LDFLAGS_GL="-Wl,-rpath,../../Mesa/lib -L../../Mesa/lib" OPENGL_LIBS="-lGL -lGLU" $WXCONFIGURE_OPTION
+    if test $? != 0 ; then
+      { { echo "$as_me:$LINENO: error: A problem occurs durring wxWidgets library configuration. Please fix the problem and try again." >&5
+echo "$as_me: error: A problem occurs durring wxWidgets library configuration. Please fix the problem and try again." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
   else
     # use OpenGL system libraries
     ../configure $WXCONFIGURE_OPTION
@@ -13654,6 +13676,11 @@ echo "$as_me: error: TODO: configurer wxWidgets pour MACOSX" >&2;}
   echo "---> Compiling wxWidgets library."
   # compile the lib
   make
+  if test $? != 0 ; then
+    { { echo "$as_me:$LINENO: error: A problem occurs durring wxWidgets library compilation. Please fix the problem and try again." >&5
+echo "$as_me: error: A problem occurs durring wxWidgets library compilation. Please fix the problem and try again." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
   echo "---> Compiling wxWidgets contrib xrc library."
   cd contrib/src/xrc
   # compile xrc lib (xml resource lib)
@@ -13672,9 +13699,13 @@ echo "$as_me: error: TODO: configurer wxWidgets pour MACOSX" >&2;}
   mkdir -p $OLDDIR/../wxWidgets/contrib
   mkdir -p $OLDDIR/../wxWidgets/contrib/include
   mkdir -p $OLDDIR/../wxWidgets/lib
+  # copy includes
   cp -r include/* $OLDDIR/../wxWidgets/include/
   cp -r contrib/include/* $OLDDIR/../wxWidgets/contrib/include/
-  cp -r AMAYABUILD/lib/* $OLDDIR/../wxWidgets/lib/
+  cp -r AMAYABUILD/lib/wx $OLDDIR/../wxWidgets/lib/
+  # copy libraries (only .a because we dont want to share)
+  cp -pd AMAYABUILD/lib/*.a $OLDDIR/../wxWidgets/lib/
+  # copy autoconfig script (needed to setup 'Option' file)
   cp -pd AMAYABUILD/*-config $OLDDIR/../wxWidgets/
   cd $OLDDIR
   echo "---> Install wxWidgets library into Amaya. - DONE"
